apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - service.yaml
  - redis-master-deployment.yaml
  - redis-master-service.yaml
  - redis-replica-deployment.yaml
  - redis-replica-service.yaml
